### ISSUE TITLE
Why this package isn't in melpa?

### ISSUE THREAD

**Issue by ema2159** [manateelazycat/awesome-tab#34]
I'm really interested in this package, I would like to contribute to it and add features like all the icons integration. There isn't really any decent tab plugins for Emacs so if this package gets to mature well it could become a really really useful tool

**Comment by manateelazycat** [comment]
Why don't I want to put my Emacs plugin on MELPA?

I have been playing Emacs for more than a decade and have written a lot of Emacs plugins. Many people have suggested putting my Emacs plugin on MELPA.

My answer has always been: NO

I will write the reason today. If someone asks me later, I can send this answer directly, without repeating the answer:

I promised my friend a year ago that rgr contributed org-w3m.el to the main branch of Emacs. It took me a lot of time, almost coding one night, and merging the code for 2 months.
Later, after listening to rgr's suggestion, after putting all the plug-ins into EmacsWiki, my mailbox has been bombarded by various emacser for more than ten years. The open source software is like this, the creation time is short, but the maintenance time is far. Far more than the time of creation, including the multi-term.el, sdcv.el, auto-install.el, anything.el, auto-complete.el plug-ins that we often use, I have maintained more than ten years, although I am really happy to be able to help emacser all over the world, but maintaining the plugin really takes me a lot of time.
It is true that MELPA/Package.el is very convenient for users, and will let more people know the plug-ins I wrote, but it also means that there will be hundreds of times for users to give me an issue and suggestions. I am a person who does not like to reject others. People, if hundreds of times users send issues and suggestions, I will certainly not sleep to improve my plug-in, which will inevitably take up my time with my family. Considering more, I hope more time for family to be happy, and Not to make emacser in the world happier, even though they are very friendly and cute.
Writing Emacs plugins and understanding the details of various plugins, I spent countless days and nights, although MELPA allows 90% of Emacs users to automatically download and install (including dependencies) with one click, but at the same time it has made too many moves. The user of the brain will not search and research when encountering problems, only complain, and finally give up Emacs. Emacs is genetically not an out-of-the-box IDE. You may not start Elisp programming at first, but in the end you must learn Elisp. Programming will make Emacs the best tool for the Dragon Slayer. So, I don't want everyone to become a foolish MELPA user, that will only make you lose the ability to solve Emacs problems, and finally push more users away. Emacs, not the philosophy of embracing Emacs
I have passed the days when I proved my personal abilities to the world. In the next few decades, I hope to spend more time learning new techniques and accompanying my family, instead of endlessly tossing Emacs and tossing Emacs. Not learning advanced technology, like a craftsman who will only temper a sword but have no time to practice swordsmanship. Emacs is always a tool to explore curiosity. Emacs itself should not be a goal of learning.
In addition to technology, I have a lot of my own insights into the details of the product. I prefer to make some plug-ins that are out of the box and elegant in detail. It is just the kind of feeling that is just enough, not too many and too many. I don't like it. Like the traditional open source software developers, the Swiss army knife, which is very rich in functions, is not used by many function authors. If you use too many people, it will be difficult to adjust. Finally, the plug-ins you write don’t even like me. It’s too boring. And those who refuse to make constructive comments, I am a little bit uncomfortable, so my plug-in is left for those emacser who have the same sample taste as me. It is the most comfortable in the state of being together.
I have been very tired in the past ten years, always giving myself too much burden.

In the days to come, I hope to live for my curiosity and personal habits. I am very happy to like my work. I don't like my work. I welcome you to continue exploring. This is the simplest and most happy day.

**Comment by manateelazycat** [comment]
@ema2159 Just commit patch, above is why i don't like MELPA. ;)

**Comment by ema2159** [comment]
> Why don't I want to put my Emacs plugin on MELPA?
> 
> I have been playing Emacs for more than a decade and have written a lot of Emacs plugins. Many people have suggested putting my Emacs plugin on MELPA.
> 
> My answer has always been: NO
> 
> I will write the reason today. If someone asks me later, I can send this answer directly, without repeating the answer:
> 
> I promised my friend a year ago that rgr contributed org-w3m.el to the main branch of Emacs. It took me a lot of time, almost coding one night, and merging the code for 2 months.
> Later, after listening to rgr's suggestion, after putting all the plug-ins into EmacsWiki, my mailbox has been bombarded by various emacser for more than ten years. The open source software is like this, the creation time is short, but the maintenance time is far. Far more than the time of creation, including the multi-term.el, sdcv.el, auto-install.el, anything.el, auto-complete.el plug-ins that we often use, I have maintained more than ten years, although I am really happy to be able to help emacser all over the world, but maintaining the plugin really takes me a lot of time.
> It is true that MELPA/Package.el is very convenient for users, and will let more people know the plug-ins I wrote, but it also means that there will be hundreds of times for users to give me an issue and suggestions. I am a person who does not like to reject others. People, if hundreds of times users send issues and suggestions, I will certainly not sleep to improve my plug-in, which will inevitably take up my time with my family. Considering more, I hope more time for family to be happy, and Not to make emacser in the world happier, even though they are very friendly and cute.
> Writing Emacs plugins and understanding the details of various plugins, I spent countless days and nights, although MELPA allows 90% of Emacs users to automatically download and install (including dependencies) with one click, but at the same time it has made too many moves. The user of the brain will not search and research when encountering problems, only complain, and finally give up Emacs. Emacs is genetically not an out-of-the-box IDE. You may not start Elisp programming at first, but in the end you must learn Elisp. Programming will make Emacs the best tool for the Dragon Slayer. So, I don't want everyone to become a foolish MELPA user, that will only make you lose the ability to solve Emacs problems, and finally push more users away. Emacs, not the philosophy of embracing Emacs
> I have passed the days when I proved my personal abilities to the world. In the next few decades, I hope to spend more time learning new techniques and accompanying my family, instead of endlessly tossing Emacs and tossing Emacs. Not learning advanced technology, like a craftsman who will only temper a sword but have no time to practice swordsmanship. Emacs is always a tool to explore curiosity. Emacs itself should not be a goal of learning.
> In addition to technology, I have a lot of my own insights into the details of the product. I prefer to make some plug-ins that are out of the box and elegant in detail. It is just the kind of feeling that is just enough, not too many and too many. I don't like it. Like the traditional open source software developers, the Swiss army knife, which is very rich in functions, is not used by many function authors. If you use too many people, it will be difficult to adjust. Finally, the plug-ins you write don’t even like me. It’s too boring. And those who refuse to make constructive comments, I am a little bit uncomfortable, so my plug-in is left for those emacser who have the same sample taste as me. It is the most comfortable in the state of being together.
> I have been very tired in the past ten years, always giving myself too much burden.
> 
> In the days to come, I hope to live for my curiosity and personal habits. I am very happy to like my work. I don't like my work. I welcome you to continue exploring. This is the simplest and most happy day.

Wow, I didn't expected such a deep answer jaja, but I understand and completely respect your position about this. Would you be ok if I forked this package in a future and share it? I'd really like to build a powerful tabs plugin and I have a ton of ideas.

**Comment by manateelazycat** [comment]
Feel free to that.

**Comment by manateelazycat** [comment]
> I'm really interested in this package, I would like to contribute to it and add features like all the icons integration. There isn't really any decent tab plugins for Emacs so if this package gets to mature well it could become a really really useful tool

If you want icon render in tab, this patch has do that: https://github.com/manateelazycat/awesome-tab/commit/ae98cef5c9fe2b8674c705f1772400f0caf10a74

You can watch result: https://github.com/manateelazycat/awesome-tab/blob/master/screenshot.png

**Comment by ema2159** [comment]
Hi! @manateelazycat I've been working on my own version of this plugin! I forked it and I've been adding my own features. I also managed to include icons. Go check it out if you want!

**Comment by manateelazycat** [comment]
> Hi! @manateelazycat I've been working on my own version of this plugin! I forked it and I've been adding my own features. I also managed to include icons. Go check it out if you want!

Maybe we should develop together so that everyone doesn't have to waste time developing the same features. ;)

**Comment by ema2159** [comment]
That would be great, that was my idea from the very beginning, the thing is that I thought you didn't liked MELPA and that's why I asked for permission to fork your repo so I could develop a plugin that I could upload to MELPA. What do you think?

**Comment by ema2159** [comment]
> > I'm really interested in this package, I would like to contribute to it and add features like all the icons integration. There isn't really any decent tab plugins for Emacs so if this package gets to mature well it could become a really really useful tool
> 
> If you want icon render in tab, this patch has do that: [ae98cef](https://github.com/manateelazycat/awesome-tab/commit/ae98cef5c9fe2b8674c705f1772400f0caf10a74)
> 
> You can watch result: https://github.com/manateelazycat/awesome-tab/blob/master/screenshot.png

I managed this:
![image](https://user-images.githubusercontent.com/17773218/59970053-4e7cc980-951a-11e9-8eec-309e37252c95.png)

I managed to preserve the icon colors although I've been unable to put it behind the separator. Also, some icons are unaligned like the Elisp icon because of the inconsistency problems of `all-the-icons` fonts. I would like to figure out a solution to that problem.
