### ISSUE TITLE
wrong icon color  and font face

### ISSUE THREAD

**Issue by Eason0210** [manateelazycat/awesome-tab#96]
When update to new version. The font of Tab doesn't follow theme's setting. And the color of icon shows black color when the buffer is dired mode or log message.  

![image](https://user-images.githubusercontent.com/47546452/97253157-b21db200-1846-11eb-8b8b-0f61acd2e2b3.png)

**Comment by AmaiKinono** [comment]
I noticed similar problems using the default theme:

![image](https://user-images.githubusercontent.com/28714352/97284912-946b3f80-187c-11eb-9857-339329e7e417.png)

But the color shows correctly on my side.

It works with doom-themes:

![image](https://user-images.githubusercontent.com/28714352/97285142-d0060980-187c-11eb-8365-3aafc2ea21a0.png)

That's why I didn't notice the problem when I submit the patch.

The following code solves the font problem:

``` elisp
(set-face-attribute 'tab-line nil :inherit 'default)
```

You see sans-serif fonts because the face `tab-line` inherits `variable-pitch` by default.

I have no idea on the color problem. Does it happen with `$ emacs -Q`?

**Comment by Eason0210** [comment]
You are right.  `(set-face-attribute 'tab-line nil :inherit 'default)` solves the font face issue.

**Comment by manateelazycat** [comment]
Newest version has fixed this issue.

**Comment by AmaiKinono** [comment]
There's still the color problem. It can be easily solved by:

``` elisp
(set-face-attribute 'tab-line nil
                    :inherit 'default
                    :foreground 'unspecified)
```

Emacs specifies foreground and background for `tab-line`, but not for `header-line` (I don't know why the have such a strong opinion on what should tab-line look like). I suspect the background color would also cause problems later. And, if Emacs people decide to add more attributes, then we'll have to deal with them.

To solve it once and for all:

``` elisp
(face-spec-set awesome-tab-display-line
               '((t :inherit 'default))
               'face-defface-spec)
```

Which redefines the face, rather then overriding the attributes of it.

cc @manateelazycat

**Comment by manateelazycat** [comment]
Thanks for tips, I have commit new patch to fix this issue.
